# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macOS 10.13'

steps:  
- bash: |
    pip install virtualenv
    virtualenv -p python venv
    source venv/bin/activate
    python -V && pip -V
    pip install -r requirements.txt
  displayName: 'Create Python2 Virtualenv'

- script: $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-23;google_apis;x86"
  displayName: 'sdkmanager install system-image'

- script: $ANDROID_HOME/tools/bin/avdmanager create avd --device "Nexus 5" --package "system-images;android-23;google_apis;x86" --abi google_apis/x86 --name "Nexus5Emu"
  displayName: 'create AVD'

- script: $(which npm) install -g appium wd
  displayName: 'npm install'

- bash: |
    source venv/bin/activate
    $ANDROID_HOME/emulator/emulator -avd Nexus5Emu &
    echo $! >> emu.pid
    echo "Started Emu"
    appium &
    echo $! >> appium.pid
    echo "Started Appium"
    python test-appium.py
    echo "Quitting Processes"
    kill $(cat appium.pid)
    sleep 15
    adb devices
    adb kill-server
    kill -9 $(cat emu.pid)
    ps ax | grep Nexus5Emu
    echo "Done"
  displayName: 'test appium'
