# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macOS 10.13'

steps:
- script: appium --version || true
  displayName: 'check appium'

- script: $(which npm) install -g appium wd
  displayName: 'npm install'

- script: $(which pip) install -r requirements.txt
  displayName: 'pip install requirements'

- script: sdkmanager --help || true
  displayName: 'check sdkmanager'

- script: $(which sdkmanager) --list
  displayName: 'sdkmanager list'

- script: avdmanager create avd --device "Nexus 5" --package "system-images;android-23;google_apis;x86" --abi google_apis/x86 --name "Nexus5Emu"
  displayName: 'create AVD'

- script: emulator Nexus5Emu
  displayName: 'run AVD'

- script: python test-appium.py
  displayName: 'test appium'
