# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macOS 10.13'

steps:
- script: $ANDROID_HOME/tools/bin/avdmanager list
  displayName: 'avdmanager list'

- script: $ANDROID_HOME/tools/bin/sdkmanager --list
  displayName: 'sdkmanager list'

- script: python -V && pip -V; python -m ensurepip; python -V && pip -V
  displayName: 'python and pip versions'

- script: $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-23;google_apis;x86"
  displayName: 'sdkmanager install system-image'

- script: $ANDROID_HOME/tools/bin/avdmanager create avd --device "Nexus 5" --package "system-images;android-23;google_apis;x86" --abi google_apis/x86 --name "Nexus5Emu"
  displayName: 'create AVD'

- script: $ANDROID_HOME/tools/bin/avdmanager list avd
  displayName: 'list AVDs'

- script: $(which npm) install -g appium wd
  displayName: 'npm install'

- script: pip install -r requirements.txt
  displayName: 'pip install requirements'

- script: python test-appium.py
  displayName: 'test appium'
